---
- name: Delete legacy dnsmasq daemonset
  kube:
    name: dnsmasq
    namespace: "{{system_namespace}}"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "ds"
    state: absent
  when: inventory_hostname == groups['kube-master'][0]
- name: Delete legacy dnsmasq deamonset manifest
  file:
    path: "{{kube_config_dir}}/dnsmasq-ds.yml"
    state: absent
